### ISSUE TITLE
Landing page for Gitte

### ISSUE THREAD

**Issue by jj-lucas** [jackjonesfashion/wiz#149]
Anna Sarah will deliver simple mockup + pics + reviewed EN text. Not nationalized. 
To be live around the 20th feb,

**Comment by jj-lucas** [comment]
http://jackjones.de/Terms-and-conditions/jj-sustainability-terms-and-conditions,de_DE,pg.html

**Comment by jeppeolesen** [comment]
What's going on here? Isn't this a front-end task?
