### ISSUE TITLE
Setup content flows for ADPT

### ISSUE THREAD

**Issue by jj-lucas** [jackjonesfashion/wiz#173]
* Having a meeting soon to define scope of the project and our involvement

**Comment by jj-lucas** [comment]
ADPT will be launched in July

**Comment by jj-lucas** [comment]
Acoording to Katrine 23/4, based on her talk with eCom in Amsterdam, ADPT will not fall on our shoulders

**Comment by jj-lucas** [comment]
bye bye

**Comment by jeppeolesen** [comment]
Y u no clz dis?

![](http://www.reactiongifs.com/r/coat.gif)
