### ISSUE TITLE
"Sentinel" dashboard for Operations / Creative

### ISSUE THREAD

**Issue by jj-lucas** [jackjonesfashion/wiz#189]
* Capability to assign task to a team member
* Automatic reminder if milestone is not met
* Visual overview of incoming activities
* Prioritization from Campaign to express urgency

**Comment by jeppeolesen** [comment]
Creatives reaction:
![](http://www.reactiongifs.com/r/djco.gif)

**Comment by jj-lucas** [comment]
Sentinel enforcing deliverables: 
![terminator-2-crushed-skull-o](https://cloud.githubusercontent.com/assets/2851890/6616814/75bffbfe-c8b2-11e4-89ce-69add35309e4.gif)

**Comment by jj-lucas** [comment]
* hook up to image request list (but be aware that images are delivered in groups on weekly basis
