### ISSUE TITLE
20/7 Deanim Dealers campaign

### ISSUE THREAD

**Issue by jj-lucas** [jackjonesfashion/wiz#279]
20/7 live
- instagram feed (maybe only selected pics)
- possibly archive of topics
- content updated regularly over a 2/3 months span
- videos
- products / fits focus

**Comment by jj-lucas** [comment]
waiting for mockups

**Comment by jj-lucas** [comment]
Project's dead, baby. Project's dead.

**Comment by jeppeolesen** [comment]
A moment of silence for the fallen.
