### ISSUE TITLE
Campaign flow - Look at stuffs

### ISSUE THREAD

**Issue by jeppeolesen** [jackjonesfashion/wiz#299]
Update some text
![download](https://cloud.githubusercontent.com/assets/1243023/7934909/3ac04ca6-092c-11e5-9ab4-1931583a1650.jpg)

![image](https://cloud.githubusercontent.com/assets/1243023/7934913/415456de-092c-11e5-8668-b4a544152e82.png)

**Comment by jj-lucas** [comment]
@jeppeolesen yo

**Comment by jeppeolesen** [comment]
Yo. Sup?

Jeppe Hyldgaard Olesen
E-commerce Creative   /   Creative Developer
P

+4582388834

M

+4528607212

E

jeppe.olesen@bestseller.com<mailto:jeppe.olesen@bestseller.com>

W

BESTSELLER.COM<http://bestseller.com>

BESTSELLER A/S
FREDSKOVVEJ 1, 7330 BRANDE
DENMARK
[cid:image001.png@01D09D39.411EAB10]
