### ISSUE TITLE
Set up sharing by group in Google Drive

### ISSUE THREAD

**Issue by jj-lucas** [jackjonesfashion/wiz#301]
- [x] Map current users / roles
- [x] Draft user groups
- [x] Unshare everything
- [x] Share to appropriate groups

Good occasion to reorganize the folder structure on GD (#155)

https://groups.google.com/forum/#!overview

**Comment by jeppeolesen** [comment]
Ticket #301 ! Hooray !

**Comment by jj-lucas** [comment]
Google Drive Structure


Overview tools [Tech] [only]

	Source Ark [Tech, OPS, Marie] [view]

	Translations bank [Tech, Copywriters, Campaigns, Traffic] [view]

	Styles booking [Tech, Photo, Sales]


Content Flows [Tech] [only]

	Activity briefs [Tech, OPS, Creative] [view]

	Modelshots [Tech]

	Newsletter briefs [Tech, Creative, Newsletter]


Utilities [Tech] [only]

	Hemmelige kategorie generator [Tech, OPS]

	Link builder [Tech, Traffic] [view]

	Markdown products [Tech, OPS]

	PSD Translator [Tech, Creative, Traffic] [view]

	URL redirects [Tech, OPS]

	Style image list [Tech, Sales, Traffic]


Scripts [Tech]

	Deployment manager [Tech]

	jjUtils [Tech]

	Tool template [Tech]

	Merchandising tool [Tech]


-----	

Playground [Tech]

Projects [Tech]

Selected [Tech, Selected] still needed?

Shared with me ***

z_obsolete [Tech]

**Comment by jj-lucas** [comment]
Groups needed:
jj-tech
jj-ops
jj-creative
jj-facebook
jj-newsletter
jj-seo
jj-campaigns
jj-photo
jj-copywriters
jj-sales

**Comment by jj-lucas** [comment]
Waiting for Nik to decide which friday + weekend is best for him. Gonna shut down all tools, unshare everything and set up sharing by group.

**Comment by jj-lucas** [comment]
- add user to group (no mails)
- have him navigate to top level folders + add to drive
- maybe authorize some scripts (ensure they have DoGet() webapp and add link to docs for easy authorization)

- to unshare, remove from group
