### ISSUE TITLE
Mobile category headlines

### ISSUE THREAD

**Issue by katrine-olesen** [jackjonesfashion/wiz#331]
Some mobile categories have a text in the heading / banner, where as other do not.
In addition to this, the filter is also missing on these categories.

Ex. printed t-shirts vs. training t-shirt category on Mobile.
Please see the difference in attached screenshots

![image](https://cloud.githubusercontent.com/assets/7114538/8248741/d2443ff4-1662-11e5-9a23-f43a743dab69.png)

![image](https://cloud.githubusercontent.com/assets/7114538/8248748/ddf1fbfc-1662-11e5-8c34-7ed036ca886a.png)

**Comment by katrine-olesen** [comment]
the same applies for the sportswear category for mobile

**Comment by jj-lucas** [comment]
Printed tshirts (with heading)
![image](https://cloud.githubusercontent.com/assets/2851890/8248824/b1be6bfa-1663-11e5-835f-b19ed643956a.png)

Training tshirts (without)
![image](https://cloud.githubusercontent.com/assets/2851890/8248831/c82d5ee6-1663-11e5-9387-13d0c8acc68f.png)

**Comment by jj-lucas** [comment]
@katrine-olesen if you decide having all mobile categories displaying the text, i can change the ALT URLs programmatically. Just make sure there's no special ones among those listed in the ark. (suits.. blazers.. gilet..)

**Comment by katrine-olesen** [comment]
i think we should change them
will you please proceed with it when you have time!

**Comment by jj-lucas** [comment]
Will do. Should I create a new Ark worksheet for ALT URLs, to document all the "special" ones?

**Comment by katrine-olesen** [comment]
Yes i think this is probably a good idea, so we kan keep track of alle category settings.

**Comment by jj-lucas** [comment]
Worksheet created. On deploying the ALT URLs, this issue will get fixed.
The correct mobile ALT URLs are already in the worksheet, but special categories need to be customized.
Trine will deploy when she's ready.

![image](https://cloud.githubusercontent.com/assets/2851890/8349826/653178b0-1b20-11e5-8a7b-f08c5b99a44c.png)
