### ISSUE TITLE
30 days return - CH + UK ( ROE) 

### ISSUE THREAD

**Issue by kevin-kristensen** [jackjonesfashion/wiz#335]
I averterer på forsiden af den østrigske shop med gratis returfragt for ordrer over 60€. Dette er ikke korrekt. Alle returpakker fra Østrig skal betale 3,95€ i returfragt.

 
![image](https://cloud.githubusercontent.com/assets/12713979/8304077/58f5af7c-19a3-11e5-8cfa-810e33685262.png)

http://jackjones.com/shop/jack-jones,de_AT,sc.html

**Comment by jj-lucas** [comment]
Also on UK and CH

**Comment by jj-lucas** [comment]
@Kay3nta FYI

**Comment by jj-lucas** [comment]
the changes have been deployed, and will be live tomorrow

**Comment by kevin-kristensen** [comment]
Thanks ;)
