### ISSUE TITLE
Hero spot - category is empty - Live on the site 

### ISSUE THREAD

**Issue by kevin-kristensen** [jackjonesfashion/wiz#341]
Hi Lucas. 

Just tested the hero spot and could see that the shorts category was empty. 

Do you know why? 

Thank you in advance.

**Comment by jj-lucas** [comment]
Hej @kevin-kristensen , sorry, just noticed this task:
The category was set to go online on the 2nd.
![image](https://cloud.githubusercontent.com/assets/2851890/8428593/06d89a42-1f20-11e5-8389-7e1a73287f2c.png)

AFAIK @katrine.olesen is already taking action
