### ISSUE TITLE
We cannot select a size - 12092928

### ISSUE THREAD

**Issue by kevin-kristensen** [jackjonesfashion/wiz#356]
Hi Lucas,

The customer cannot select a size, but can still put the item in the shopping basket?
Please check, thanks

http://bestseller.nl/on/demandware.store/Sites-NL-Site/nl_NL/Product-Show?pid=12092928&dwvar_12092928_colorPattern=12092928_Black

**Comment by jj-lucas** [comment]
I created a JIRA to address the issue. For competition, follow its status: https://bestseller.jira.com/browse/OPS-29314
