### ISSUE TITLE
Item Number: 12086953 - FAUX LEATHER SNEAKERS - no sizes

### ISSUE THREAD

**Issue by kevin-kristensen** [jackjonesfashion/wiz#357]
Hi Lucas, 

When trying to order this item there is no sizes available.

May I know when the size would be available or if it’s completely out of stock?

http://bestseller.com/jack-jones/sneakers/jjbrooklyn-pu-sneaker-cloud-dancer/12086953,en_GB,pd.html?dwvar_12086953_colorPattern=12086953_CloudDancer

Thank you in advance.

Best.

**Comment by jj-lucas** [comment]
I created a JIRA to address the issue. For competition, follow its status: https://bestseller.jira.com/browse/OPS-29314
