### ISSUE TITLE
Sizes are missing 

### ISSUE THREAD

**Issue by kevin-kristensen** [jackjonesfashion/wiz#369]
Hi Lucas, 

The sizes are missing on these jackets. Will you please report it? 

http://jackjones.dk/jack-jones/denim/jjclyde-jjjacket-jos-788/12101292,da_DK,pd.html?dwvar_12101292_colorPattern=12101292_BlueDenim

http://jackjones.dk/jack-jones/leather/jjprmike-jacket/12096800,da_DK,pd.html?dwvar_12096800_colorPattern=12096800_Black_470700#lcgid=jj-j-shop-outerwear

http://jackjones.dk/jack-jones/light/jjtctian-flexshell-jacket/12090585,da_DK,pd.html?dwvar_12090585_colorPattern=12090585_Black#lcgid=jj-j-shop-outerwear

http://jackjones.dk/jack-jones/functional/jjtcwhiz-flexshell-jkt/12090026,da_DK,pd.html?dwvar_12090026_colorPattern=12090026_NavyBlazer#lcgid=jj-j-shop-outerwear

Thank you in advance.

**Comment by kevin-kristensen** [comment]
Also these two: 

12096526 - http://jackjones.dk/jack-jones/l-s-shirts/jjprdobby-shirt-l-s-plain/12096526,da_DK,pd.html?dwvar_12096526_colorPattern=12096526_Port_479745

12084146 - http://jackjones.dk/jack-jones/tailored-trousers/jjroy-trousers-black-noos/12084146,da_DK,pd.html?dwvar_12084146_colorPattern=12084146_Black_429883

Thanks.

**Comment by jj-lucas** [comment]
@katrine-olesen please investigate

**Comment by katrine-olesen** [comment]
i have created a service desk ticket, you can close it here!

**Comment by jj-lucas** [comment]
https://bestseller.jira.com/servicedesk/customer/portal/29/SDO-136
