### ISSUE TITLE
Premium brandsite 

### ISSUE THREAD

**Issue by kevin-kristensen** [jackjonesfashion/wiz#390]
Hi Lucas, 

Will you please change the link on the Premium brandsite: http://jackjones.dk/jack-jones/casual-shoes/jjorlando-cotton-low-whisper-white/12090211,da_DK,pd.html?dwvar_12090211_colorPattern=12090211_WhisperWhite

It should link to the right shoes that just went online today: http://jackjones.dk/jack-jones/casual-shoes/jjgalaxy-leather-sneaker-bright-white/12103895,da_DK,pd.html?dwvar_12103895_colorPattern=12103895_BrightWhite#lcgid=jj-j-shop-shoes

Thank you in advance.

**Comment by jj-lucas** [comment]
These changes should be addressed via Gitte, who coordinates brandsites content.
