### ISSUE TITLE
Tech brandsite 

### ISSUE THREAD

**Issue by kevin-kristensen** [jackjonesfashion/wiz#391]
Hi Lucas, 

Will you also change the link on the Tech brandsite:  http://jackjones.dk/jack-jones/sneakers/jjadjust-mesh-fx8-black/12095566,da_DK,pd.html?dwvar_12095566_colorPattern=12095566_Black

It should link to the right shoes that just went online today: http://jackjones.dk/jack-jones/sneakers/jjadjust-mesh-fx8-asphalt/12095565,da_DK,pd.html?dwvar_12095565_colorPattern=12095565_Asphalt

Thank you in advance.

**Comment by jj-lucas** [comment]
These changes should be addressed via Gitte, who coordinates brandsites content.
