### ISSUE TITLE
Tool - Storefront Promo Boxes

### ISSUE THREAD

**Issue by jeppeolesen** [jackjonesfashion/wiz#392]
https://github.com/jackjonesfashion/tasks/issues/188

**Comment by jj-lucas** [comment]
> What:
> Min 2 - Max 8 promoboxes introduced below the hero
Boxes contain one image, CTA, description and link.

> How:
> Content slots, same as always. Template updated to support it.
> How often:
> Once a week, following brand-sites and WR schedule

> Who:
> Products and Focus: Jesper F + Brands
> Copy: Karina
> Images: Graphics

> Why:
> Because MM said so

**Comment by jj-lucas** [comment]
https://docs.google.com/spreadsheets/d/1B5VjSjIncLcD1n-1s74M-AavyP9DhDELUiSBx23PeDI/edit#gid=0
