### ISSUE TITLE
Update footer links

### ISSUE THREAD

**Issue by jj-lucas** [jackjonesfashion/wiz#77]
JACK & JONES office: http://www.aboutbestseller.com/en/JobsContent/Search.aspx?CoId=0&CaId=0&BrId=8087&JlId=0&RId=0

JACK & JONES store: http://www.aboutbestseller.com/en/JobsContent/Search.aspx?CoId=0&CaId=0&BrId=44983&JlId=0&RId=0

**Comment by jj-lucas** [comment]
Foot links 
Hey Lucas we need to slice the JJ find job link in the footer in to two Find job in office / find job in store -link

**Comment by jj-lucas** [comment]
Francoise has been asked to deliver translations, ping her when she comes back

**Comment by jj-lucas** [comment]
Will do in english first, myself

**Comment by jj-lucas** [comment]
Danish:

Job & Karriere butik
Job & Karriere kontor

English:
Jobs & Careers Stores
Jobs & Careers Office


Links: 
JACK & JONES office: http://www.aboutbestseller.com/en/JobsContent/Search.aspx?CoId=0&CaId=0&BrId=8087&JlId=0&RId=0

JACK & JONES store: http://www.aboutbestseller.com/en/JobsContent/Search.aspx?CoId=0&CaId=0&BrId=44983&JlId=0&RId=0

**Comment by jeppeolesen** [comment]
Created new ticket for this in "Tasks" board
